name: Example for actions/changed-files

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/actions/changed-files/action.yaml
      - .github/workflows/example-changed-files.yaml

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/changed-files
        id: changed-files
      - run: |
          echo "Changed files: "
          echo "${{ steps.changed-files.outputs.files }}"

  with-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/changed-files
        id: changed-files
        with:
          base-ref: ${{ github.event.pull_request.base.sha }}
      - run: |
          echo "Changed files: "
          echo "${{ steps.changed-files.outputs.files }}"
