name: Renovate Config

on:
  workflow_call:
    secrets:
      GH_PAT_FOR_RENOVATE:
        required: false
  push:
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:
  setup:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      major-version: ${{ steps.version.outputs.renovate }}
      is-set-pat-for-renovate: ${{ steps.gh-pat-for-renovate.outputs.is-set }}
    steps:
      - name: Get latest major renovate version
        id: version
        run: |
          echo "::set-output name=renovate::$(npm show renovate version --no-update-notifier | cut -d . -f 1)"

      - name: Check exists GH_PAT_FOR_RENOVATE
        env:
          GH_PAT_FOR_RENOVATE: ${{ secrets.GH_PAT_FOR_RENOVATE }}
        id: gh-pat-for-renovate
        if: ${{ env.GH_PAT_FOR_RENOVATE != '' }}
        run: echo "::set-output name=is-set::true"


  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-renovate-major-v${{ needs.version.outputs.major-version }}
      - run: npx --package renovate -c 'renovate-config-validator'

  dru-run:
    name: Dry run
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.is-set-pat-for-renovate == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-renovate-major-v${{ needs.version.outputs.major-version }}
      - env:
          RENOVATE_CONFIG_FILE: renovate.json5
          LOG_LEVEL: debug
        run: npx renovate --token ${{ secrets.GH_PAT_FOR_RENOVATE }} --dry-run ${{ github.repository }}
