name: Tagging and Release
run-name: Tagging ${{ inputs.version }}

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      isMajorVersion:
        type: boolean
        required: false
        default: true
      isRelease:
        type: boolean
        required: false
        default: true

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Tagging version (ex: v1.0.1)"
        required: true
      isMajorVersion:
        type: boolean
        description: If true, it will update the MAJOR version of the tag.
        default: true
      isRelease:
        type: boolean
        description: If true, it will create a GitHub Release
        default: true

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git tag ${{ inputs.version }}
          git push --tags origin ${{ inputs.version }}

  update-major-version:
    runs-on: ubuntu-latest
    if: ${{ inputs.isMajorVersion }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          MAJOR_VERSION=$(echo ${{ inputs.version }} | awk -F'.' '{print $1}')
          echo $MAJOR_VERSION
          git tag --force $MAJOR_VERSION
          git push --force --tags origin $MAJOR_VERSION

  create-release:
    runs-on: ubuntu-latest
    if: ${{ inputs.isRelease }}
    needs: tagging
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh release create ${{ inputs.version }} --generate-notes
