name: Renovate Config

on: 
  workflow_call:
  push:
    paths:
      - .github/workflows/validate-renovate-config.yaml
      - renovate.json5    

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest major renovate version
        id: version
        run: |
          echo "::set-output name=renovate::$(npm show renovate version --no-update-notifier | cut -d . -f 1)"
          echo ${{ steps.version.outputs.renovate }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-renovate-major-v${{ steps.version.outputs.renovate }}
      - run: npx --package renovate -c 'renovate-config-validator'
